### PR TITLE
Added JRuby support.  Fork is not supported in JRuby so now starting …

### PR DESCRIPTION
**Pull request by ebadiere**
…a thread.

Didn't follow instructions.  Created feature branch after the fact.  Creating now to limit damage and off apologies.

### CODE REVIEW

**Comment by ebadiere** [comment]
Changed polling to use the RestClient get.

**Comment by vpereira** [comment]
Hm, I see two pull requests there.. did you send it accidentally or are they unrelated?

**Comment by vpereira** [comment]
would you mind to actually send your pull request to the upstream https://github.com/vpereira/owasp_zap ? thats where I do the development :)

**Comment by vpereira** [comment]
closed

**Pull request closed without merging**
